import { Course, Assignment, GradeItem, SystemNotification, UserProfile } from './types';

export const mockUserProfile: UserProfile = {
  id: 'usr_101',
  email: 'felix.vance@apex.edu',
  name: 'Felix Vance',
  role: 'student',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  gpa: 3.84,
  targetGpa: 4.00,
  major: 'B.Sc. Computer Science',
  studentId: 'STU-2026-9482',
  joinDate: 'September 2024',
};

export const mockAdminProfile: UserProfile = {
  id: 'usr_007',
  email: 'admin.clara@apex.edu',
  name: 'Dean Clara Oswald',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  gpa: 4.00,
  targetGpa: 4.00,
  major: 'Administration Office',
  studentId: 'ADM-1002-005',
  joinDate: 'January 2020',
};

export const mockCourses: Course[] = [
  {
    id: 'cs-401',
    title: 'Advanced Software Architecture',
    code: 'CS-401',
    lecturer: 'Dr. Raymond Holt',
    progress: 78,
    credits: 4,
    grade: 'A',
    image: 'https://images.unsplash.com/photo-1605379399642-870262d3d051?w=600&auto=format&fit=crop&q=80',
    description: 'Design and analysis of enterprise software systems, architectural design patterns, distributed systems routing, microservices communication, state synchronization, and fault-tolerant cloud infrastructures.',
    schedule: 'Mon, Wed 10:00 AM - 11:30 AM',
    location: 'Turing Hall, Room 402',
  },
  {
    id: 'cs-405',
    title: 'Human-Computer Interaction',
    code: 'CS-405',
    lecturer: 'Prof. Amy Santiago',
    progress: 92,
    credits: 3,
    grade: 'A+',
    image: 'https://images.unsplash.com/photo-1541462608141-27b2c7452d66?w=600&auto=format&fit=crop&q=80',
    description: 'Advanced methodologies in user research, high-fidelity interactive wireframing, heuristic evaluation parameters, cognitive models, assistive technologies, and physical interface design principles.',
    schedule: 'Tue, Thu 01:00 PM - 02:30 PM',
    location: 'Lovelace Lab, Room 105',
  },
  {
    id: 'mat-310',
    title: 'Computational Linear Algebra',
    code: 'MAT-310',
    lecturer: 'Dr. Kevin Cozner',
    progress: 45,
    credits: 4,
    grade: 'B+',
    image: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    description: 'Matrix analysis, vector spaces, eigenvalue breakdowns, singular value decompositions, and algorithmic solutions to massive algebraic equations inside standard graphics and machine learning models.',
    schedule: 'Mon, Fri 08:30 AM - 10:00 AM',
    location: 'Newton Theatre, Room 12',
  },
  {
    id: 'cs-480',
    title: 'Quantum Computing Foundations',
    code: 'CS-480',
    lecturer: 'Dr. Charles Boyle',
    progress: 60,
    credits: 3,
    grade: 'B-',
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600&auto=format&fit=crop&q=80',
    description: 'Introduction to principles of quantum mechanics, qubits, entanglement, superposition state calculations, Shor\'s factorization, Grover\'s database search algorithms, and quantum gate simulation systems.',
    schedule: 'Thu 03:00 PM - 05:30 PM',
    location: 'Planck Crypt Hall, Tech Block',
  },
  {
    id: 'bio-220',
    title: 'Molecular Biochemistry',
    code: 'BIO-220',
    lecturer: 'Prof. Rosa Diaz',
    progress: 84,
    credits: 4,
    grade: 'A-',
    image: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=600&auto=format&fit=crop&q=80',
    description: 'Chemical structures, cellular environments, metabolism cycles, enzyme catalysis pathways, lipid molecular transport, RNA synthesis, and bio-energetics sequences inside eukaryotic cells.',
    schedule: 'Tue, Fri 10:30 AM - 12:00 PM',
    location: 'Pasteur Chemistry Lab, Room 22',
  }
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg_1',
    title: 'Heuristic Validation Log',
    courseId: 'cs-405',
    courseName: 'Human-Computer Interaction',
    dueDate: '2026-05-24',
    status: 'pending',
    totalPoints: 100,
    description: 'Analyze an existing e-commerce dashboard platform using Nielsen\'s Ten Usability Heuristics. Document high severity violations in an annotated PDF layout with clear redesign models.',
  },
  {
    id: 'asg_2',
    title: 'Microservices Pipeline Architectures',
    courseId: 'cs-401',
    courseName: 'Advanced Software Architecture',
    dueDate: '2026-05-28',
    status: 'pending',
    totalPoints: 200,
    description: 'Configure and draft a fully documented Kubernetes cluster blueprint featuring load balancing, asynchronous message queuing with RabbitMQ, and centralized trace analytics with Prometheus.',
  },
  {
    id: 'asg_3',
    title: 'SVD Compression Implementation',
    courseId: 'mat-310',
    courseName: 'Computational Linear Algebra',
    dueDate: '2026-05-19',
    status: 'submitted',
    score: 94,
    totalPoints: 100,
    description: 'Write a Python script utilizing NumPy for singular value decomposition of high-resolution image matrices to compress storage by 40% while preserving critical visual thresholds.',
  },
  {
    id: 'asg_4',
    title: 'Shor\'s Simulation Sandbox',
    courseId: 'cs-480',
    courseName: 'Quantum Computing Foundations',
    dueDate: '2026-05-15',
    status: 'late',
    totalPoints: 150,
    description: 'Develop a single-qubit simulator interface visualizing rotating probability amplitudes on a sphere utilizing polar coordinate mapping.',
  },
  {
    id: 'asg_5',
    title: 'Cellular Cycle Metabolic Flowchart',
    courseId: 'bio-220',
    courseName: 'Molecular Biochemistry',
    dueDate: '2026-05-21',
    status: 'pending',
    totalPoints: 50,
    description: 'Trace and illustrate the visual pathways of the Krebs citric acid cycle, defining active enzymatic triggers and free electron outputs for class review.',
  }
];

export const mockGrades: GradeItem[] = [
  {
    id: 'grd_1',
    courseName: 'Human-Computer Interaction',
    code: 'CS-405',
    credits: 3,
    grade: 'A+',
    score: 98,
    semester: 'Spring 2026',
  },
  {
    id: 'grd_2',
    courseName: 'Advanced Software Architecture',
    code: 'CS-401',
    credits: 4,
    grade: 'A',
    score: 93,
    semester: 'Spring 2026',
  },
  {
    id: 'grd_3',
    courseName: 'Molecular Biochemistry',
    code: 'BIO-220',
    credits: 4,
    grade: 'A-',
    score: 90,
    semester: 'Spring 2026',
  },
  {
    id: 'grd_4',
    courseName: 'Computational Linear Algebra',
    code: 'MAT-310',
    credits: 4,
    grade: 'B+',
    score: 87,
    semester: 'Fall 2025',
  },
  {
    id: 'grd_5',
    courseName: 'Quantum Computing Foundations',
    code: 'CS-480',
    credits: 3,
    grade: 'B-',
    score: 81,
    semester: 'Fall 2025',
  },
  {
    id: 'grd_6',
    courseName: 'Discrete Structures & Logic',
    code: 'MAT-211',
    credits: 4,
    grade: 'A+',
    score: 99,
    semester: 'Fall 2025',
  },
  {
    id: 'grd_7',
    courseName: 'Database Management Systems',
    code: 'CS-240',
    credits: 3,
    grade: 'A',
    score: 94,
    semester: 'Spring 2025',
  }
];

export const mockNotifications: SystemNotification[] = [
  {
    id: 'not_1',
    title: 'Grade Released',
    message: 'Your grade for Heuristic Validation Log is out! Score: A+ (98/100)',
    time: '2 hours ago',
    type: 'grade',
    isRead: false,
  },
  {
    id: 'not_2',
    title: 'Assignment Due',
    message: 'Microservices Pipeline Architectures is due in 3 days. Action needed.',
    time: '6 hours ago',
    type: 'assignment',
    isRead: false,
  },
  {
    id: 'not_3',
    title: 'Campus Notice',
    message: 'System upgrade scheduled for student email platforms this Sunday at midnight.',
    time: '1 day ago',
    type: 'announcement',
    isRead: true,
  },
  {
    id: 'not_4',
    title: 'GPA Update alert',
    message: 'Congratulations! Your semester index indicates a 3.84 Cumulative GPA.',
    time: '2 days ago',
    type: 'alert',
    isRead: true,
  }
];
